universe = vanilla

executable = raw_reads_trimming.sh
arguments = $(sample)

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 7) && (Target.HasGluster == true)

transfer_input_files = PROG_instl/Trimmomatic-0.39.zip, PROG_instl/jre-8u231-linux-x64.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

log = Trimmomatic_trimming_concatLanes/DO200_S61.log
error = Trimmomatic_trimming_concatLanes/DO200_S61.error
output = Trimmomatic_trimming_concatLanes/DO200_S61.out

sample = DO200_S61

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO201_S62.log
error = Trimmomatic_trimming_concatLanes/DO201_S62.error
output = Trimmomatic_trimming_concatLanes/DO201_S62.out

sample = DO201_S62

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO202_S63.log
error = Trimmomatic_trimming_concatLanes/DO202_S63.error
output = Trimmomatic_trimming_concatLanes/DO202_S63.out

sample = DO202_S63

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO203_S64.log
error = Trimmomatic_trimming_concatLanes/DO203_S64.error
output = Trimmomatic_trimming_concatLanes/DO203_S64.out

sample = DO203_S64

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO205_S65.log
error = Trimmomatic_trimming_concatLanes/DO205_S65.error
output = Trimmomatic_trimming_concatLanes/DO205_S65.out

sample = DO205_S65

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO206_S66.log
error = Trimmomatic_trimming_concatLanes/DO206_S66.error
output = Trimmomatic_trimming_concatLanes/DO206_S66.out

sample = DO206_S66

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO207_S67.log
error = Trimmomatic_trimming_concatLanes/DO207_S67.error
output = Trimmomatic_trimming_concatLanes/DO207_S67.out

sample = DO207_S67

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO208_S68.log
error = Trimmomatic_trimming_concatLanes/DO208_S68.error
output = Trimmomatic_trimming_concatLanes/DO208_S68.out

sample = DO208_S68

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO209_S69.log
error = Trimmomatic_trimming_concatLanes/DO209_S69.error
output = Trimmomatic_trimming_concatLanes/DO209_S69.out

sample = DO209_S69

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO210_S70.log
error = Trimmomatic_trimming_concatLanes/DO210_S70.error
output = Trimmomatic_trimming_concatLanes/DO210_S70.out

sample = DO210_S70

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO211_S71.log
error = Trimmomatic_trimming_concatLanes/DO211_S71.error
output = Trimmomatic_trimming_concatLanes/DO211_S71.out

sample = DO211_S71

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO212_S72.log
error = Trimmomatic_trimming_concatLanes/DO212_S72.error
output = Trimmomatic_trimming_concatLanes/DO212_S72.out

sample = DO212_S72

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO213_S73.log
error = Trimmomatic_trimming_concatLanes/DO213_S73.error
output = Trimmomatic_trimming_concatLanes/DO213_S73.out

sample = DO213_S73

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO214_S74.log
error = Trimmomatic_trimming_concatLanes/DO214_S74.error
output = Trimmomatic_trimming_concatLanes/DO214_S74.out

sample = DO214_S74

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO215_S75.log
error = Trimmomatic_trimming_concatLanes/DO215_S75.error
output = Trimmomatic_trimming_concatLanes/DO215_S75.out

sample = DO215_S75

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO216_S76.log
error = Trimmomatic_trimming_concatLanes/DO216_S76.error
output = Trimmomatic_trimming_concatLanes/DO216_S76.out

sample = DO216_S76

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO217_S77.log
error = Trimmomatic_trimming_concatLanes/DO217_S77.error
output = Trimmomatic_trimming_concatLanes/DO217_S77.out

sample = DO217_S77

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO218_S78.log
error = Trimmomatic_trimming_concatLanes/DO218_S78.error
output = Trimmomatic_trimming_concatLanes/DO218_S78.out

sample = DO218_S78

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO220_S79.log
error = Trimmomatic_trimming_concatLanes/DO220_S79.error
output = Trimmomatic_trimming_concatLanes/DO220_S79.out

sample = DO220_S79

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO26_S80.log
error = Trimmomatic_trimming_concatLanes/DO26_S80.error
output = Trimmomatic_trimming_concatLanes/DO26_S80.out

sample = DO26_S80

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO321_S81.log
error = Trimmomatic_trimming_concatLanes/DO321_S81.error
output = Trimmomatic_trimming_concatLanes/DO321_S81.out

sample = DO321_S81

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO322_S82.log
error = Trimmomatic_trimming_concatLanes/DO322_S82.error
output = Trimmomatic_trimming_concatLanes/DO322_S82.out

sample = DO322_S82

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO323_S83.log
error = Trimmomatic_trimming_concatLanes/DO323_S83.error
output = Trimmomatic_trimming_concatLanes/DO323_S83.out

sample = DO323_S83

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO324_S84.log
error = Trimmomatic_trimming_concatLanes/DO324_S84.error
output = Trimmomatic_trimming_concatLanes/DO324_S84.out

sample = DO324_S84

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO325_S85.log
error = Trimmomatic_trimming_concatLanes/DO325_S85.error
output = Trimmomatic_trimming_concatLanes/DO325_S85.out

sample = DO325_S85

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO326_S86.log
error = Trimmomatic_trimming_concatLanes/DO326_S86.error
output = Trimmomatic_trimming_concatLanes/DO326_S86.out

sample = DO326_S86

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO327_S87.log
error = Trimmomatic_trimming_concatLanes/DO327_S87.error
output = Trimmomatic_trimming_concatLanes/DO327_S87.out

sample = DO327_S87

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO328_S88.log
error = Trimmomatic_trimming_concatLanes/DO328_S88.error
output = Trimmomatic_trimming_concatLanes/DO328_S88.out

sample = DO328_S88

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO329_S89.log
error = Trimmomatic_trimming_concatLanes/DO329_S89.error
output = Trimmomatic_trimming_concatLanes/DO329_S89.out

sample = DO329_S89

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO330_S91.log
error = Trimmomatic_trimming_concatLanes/DO330_S91.error
output = Trimmomatic_trimming_concatLanes/DO330_S91.out

sample = DO330_S91

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO331_S92.log
error = Trimmomatic_trimming_concatLanes/DO331_S92.error
output = Trimmomatic_trimming_concatLanes/DO331_S92.out

sample = DO331_S92

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO332_S93.log
error = Trimmomatic_trimming_concatLanes/DO332_S93.error
output = Trimmomatic_trimming_concatLanes/DO332_S93.out

sample = DO332_S93

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO333_S94.log
error = Trimmomatic_trimming_concatLanes/DO333_S94.error
output = Trimmomatic_trimming_concatLanes/DO333_S94.out

sample = DO333_S94

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO335_S95.log
error = Trimmomatic_trimming_concatLanes/DO335_S95.error
output = Trimmomatic_trimming_concatLanes/DO335_S95.out

sample = DO335_S95

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO336_S96.log
error = Trimmomatic_trimming_concatLanes/DO336_S96.error
output = Trimmomatic_trimming_concatLanes/DO336_S96.out

sample = DO336_S96

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO337_S97.log
error = Trimmomatic_trimming_concatLanes/DO337_S97.error
output = Trimmomatic_trimming_concatLanes/DO337_S97.out

sample = DO337_S97

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO338_S98.log
error = Trimmomatic_trimming_concatLanes/DO338_S98.error
output = Trimmomatic_trimming_concatLanes/DO338_S98.out

sample = DO338_S98

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO339_S99.log
error = Trimmomatic_trimming_concatLanes/DO339_S99.error
output = Trimmomatic_trimming_concatLanes/DO339_S99.out

sample = DO339_S99

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO33_S90.log
error = Trimmomatic_trimming_concatLanes/DO33_S90.error
output = Trimmomatic_trimming_concatLanes/DO33_S90.out

sample = DO33_S90

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO340_S100.log
error = Trimmomatic_trimming_concatLanes/DO340_S100.error
output = Trimmomatic_trimming_concatLanes/DO340_S100.out

sample = DO340_S100

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO342_S101.log
error = Trimmomatic_trimming_concatLanes/DO342_S101.error
output = Trimmomatic_trimming_concatLanes/DO342_S101.out

sample = DO342_S101

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO343_S102.log
error = Trimmomatic_trimming_concatLanes/DO343_S102.error
output = Trimmomatic_trimming_concatLanes/DO343_S102.out

sample = DO343_S102

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO344_S103.log
error = Trimmomatic_trimming_concatLanes/DO344_S103.error
output = Trimmomatic_trimming_concatLanes/DO344_S103.out

sample = DO344_S103

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO345_S104.log
error = Trimmomatic_trimming_concatLanes/DO345_S104.error
output = Trimmomatic_trimming_concatLanes/DO345_S104.out

sample = DO345_S104

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO346_S105.log
error = Trimmomatic_trimming_concatLanes/DO346_S105.error
output = Trimmomatic_trimming_concatLanes/DO346_S105.out

sample = DO346_S105

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO347_S106.log
error = Trimmomatic_trimming_concatLanes/DO347_S106.error
output = Trimmomatic_trimming_concatLanes/DO347_S106.out

sample = DO347_S106

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO35_S107.log
error = Trimmomatic_trimming_concatLanes/DO35_S107.error
output = Trimmomatic_trimming_concatLanes/DO35_S107.out

sample = DO35_S107

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO36_S108.log
error = Trimmomatic_trimming_concatLanes/DO36_S108.error
output = Trimmomatic_trimming_concatLanes/DO36_S108.out

sample = DO36_S108

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO37_S109.log
error = Trimmomatic_trimming_concatLanes/DO37_S109.error
output = Trimmomatic_trimming_concatLanes/DO37_S109.out

sample = DO37_S109

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO38_S110.log
error = Trimmomatic_trimming_concatLanes/DO38_S110.error
output = Trimmomatic_trimming_concatLanes/DO38_S110.out

sample = DO38_S110

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


log = Trimmomatic_trimming_concatLanes/DO39_S111.log
error = Trimmomatic_trimming_concatLanes/DO39_S111.error
output = Trimmomatic_trimming_concatLanes/DO39_S111.out

sample = DO39_S111

request_memory = 8GB
request_disk = 20GB
request_cpus = 1

queue


