universe = vanilla

executable = Attie_Sorcs_WGS_trimmomatic_concatLanes.sh
arguments = $(lane1) $(lane2) $(lane3) $(lane4) $(lane5) $(sample)

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 7) && (Target.HasGluster == true)

transfer_input_files = PROG_instl/Trimmomatic-0.39.zip, \
                       PROG_instl/jre-8u231-linux-x64.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# append your samples here

# e.g., sample1: Sorcs_KI1
log = Trimmomatic/Sorcs_KI1.log
error = Trimmomatic/Sorcs_KI1.error
output = Trimmomatic/Sorcs_KI1.out

lane1 = S369_L001
lane2 = S369_L002
lane3 = S369_L003
lane4 = S369_L004
lane5 = S408_L004
sample = Sorcs_KI1

request_memory = 8GB
request_disk = 32GB
request_cpus = 1

queue

# e.g., sample2: Sorcs_KI2
log = Trimmomatic/Sorcs_KI2.log
error = Trimmomatic/Sorcs_KI2.error
output = Trimmomatic/Sorcs_KI2.out

lane1 = S370_L001
lane2 = S370_L002
lane3 = S370_L003
lane4 = S370_L004
lane5 = S409_L004
sample = Sorcs_KI2

request_memory = 8GB
request_disk = 32GB
request_cpus = 1

queue
