universe = vanilla

executable = rsem_bowtie2.sh

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 7) && (Target.HasGluster == true)

transfer_input_files = ./RSEM-1.3.1.tar.gz, ./bowtie2-2.3.4-linux-x86_64.zip

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


request_memory = 32GB
request_disk = 25GB
request_cpus = 8


log = rsem_1.9M_bowtie2_log/rsem_1.9M_genes_bowtie2_DO021.log
error = rsem_1.9M_bowtie2_err/rsem_1.9M_genes_bowtie2_DO021.error
output= rsem_1.9M_bowtie2_out/rsem_1.9M_genes_bowtie2_DO021.out

queue
