universe = vanilla

executable = rsem_bowtie2_index.sh

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 7) && (Target.HasGluster == true)

transfer_input_files = PROG_instl/RSEM-1.3.1.tar.gz, \
                       PROG_instl/bowtie2-2.3.4-linux-x86_64.zip

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


request_memory = 8GB
request_disk = 15GB
request_cpus = 4


log = rsem_bowtie2_index.log
error = rsem_bowtie2_index.error
output= rsem_bowtie2_index.out

queue